version: '3.8'
services:
  db-dev:
    image: postgres:15-alpine
    container_name: postgres_dev_container
    environment:
      POSTGRES_DB: adventura_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - pgdata_dev:/var/lib/postgresql/data

volumes:
  pgdata_dev: